# Dependabot will run on day 10 of each month at 02:19 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: ""
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
